#!/bin/sh
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=slc7_amd64_gcc820
workdir=`pwd`
cmsrel CMSSW_10_6_5
cd CMSSW_10_6_5/src
eval `scramv1 runtime -sh`
scram b -j 4
cmsenv
cd ${workdir}/CMSSW_10_6_5/src/
echo this is the working dir ${workdir}
cp ${workdir}/* .



